### PR TITLE
A few changes from Monk

### PR DESCRIPTION
**Pull request by chrisullyott**
Hey there Adam! I never went ahead and made a pull request for this until now - this includes a few things that have helped us use getTweets. Let me know if you have any questions about it. Hope you're doing well!!

### CODE REVIEW

**Comment by jstayton** [comment]
Hey Adam,

I know it hasn't even been a month — and that includes the busy time around Christmas and New Years — but I'm wondering if you're still interested in maintaining this project? I haven't spoken to the team over here, but we'd potentially be interested in joining as contributors if it's not of much interest to you anymore. I don't foresee doing a whole lot other than keeping it working and updated with Twitter's API, since a good amount of Monk sites rely on it. Let me know what you think.

Hope you're doing well!

**Comment by a-am** [comment]
Hey Justin!
Yeah lately with work I haven't been able to pay any attention to the project.  Since Monk uses the plugin often, contributing to the project would be a good. Who do you want as a contributor.  

Hope your well!

**Comment by chrisullyott** [comment]
Hey guys I'll be the contributor  :+1:

**Comment by jstayton** [comment]
Thanks Adam!

**Pull request merged**
